### ISSUE TITLE
Encoding issues in the questionnaire 

### ISSUE THREAD

**Issue by olzama** [delph-in/matrix#550]
I am testing the trunk (python3 version) of the questionnaire now. There appear to be issues; some of them I know how to fix (if it is something as simple as opening a file appropriately, with utf-8 encoding specified), but other cases are more confusing to me.

In particular, if you visit this installation:

https://matrix.ling.washington.edu/trunkpy3/matrix.cgi

And simply load MiniEnglish and then click "Create grammar", you will see that python ultimately also is missing the correct encoding, but I am not sure how to fix this, because this is within the tsdb.py module of pydelphin? Except I am really surprised by that; I really doubt that something like this could be a pydelphin bug, it is much more likely that it is a matrix bug, I am juts not sure what it is because multiple things are involved.

Could maybe @goodmami give advice, where does the encoding gets lost and needs to be specified? (or fix this, haha :) ).

I mark this as urgent because ideally, @emilymbender would use the new questionnaire for her grammar engineering class which starts next week.

<img width="736" alt="Screen Shot 2020-12-29 at 3 25 53 PM" src="https://user-images.githubusercontent.com/10963114/103320472-5b6d5980-49ea-11eb-945a-7b7dc71c8868.png">

**Comment by olzama** [comment]
Oh, I now seem to remember that perhaps pydelphin relies on python3.7? That may necessitate further actions wrt the UW server.

**Comment by goodmami** [comment]
This could either be fixed by (1) configuring the server to use a default system encoding of UTF-8, (2) by patching PyDelphin to always open relations files as UTF-8 (which I plan to do, see delph-in/pydelphin#324), or (3) by parsing the relations file yourself (which I don't recommend). Even if (2) fixes the issue for you, if you have the ability to effect (1) in the server hosting the matrix, it might avoid other similar bugs, if they exist.

I'm also pinging @oepen here, because this is all due to two 'smart quotes' in the official relations file at line 174:

      e-label :string                       # edge label (as in ‘derivation’)

I don't see any reason why those can't be regular single or double quotes, which would make the file loadable as ASCII. I tried to piece together a specification for relations files [here](http://moin.delph-in.net/wiki/TsdbSchemaRfc), but I didn't mention file encodings.

> Oh, I now seem to remember that perhaps pydelphin relies on python3.7?

No, it requires Python 3.6. You can see which Python versions are supported via the 'python' badge at the top of [PyDelphin's README](https://github.com/delph-in/pydelphin/blob/develop/README.md), among other places, and whenever support for a Python version is dropped/added, I will note it in the [CHANGELOG](https://github.com/delph-in/pydelphin/blob/develop/CHANGELOG.md). For instance, Python 3.5 support was dropped and 3.8 added in [v1.2.0](https://github.com/delph-in/pydelphin/blob/develop/CHANGELOG.md#v120) last January.

**Comment by goodmami** [comment]
@olzama @bmgraves I've released PyDelphin 1.5.0, which hopefully fixes this issue for you. Can you try installing it to your virtual environment for the Matrix?

    pip install -U 'pydelphin==1.5.0'

**Comment by olzama** [comment]
The next one I am hitting is this:

<img width="791" alt="Screen Shot 2020-12-30 at 10 29 30 AM" src="https://user-images.githubusercontent.com/10963114/103373518-0b45d400-4a8a-11eb-9256-86e25686b49b.png">

I note that @goodmami said all such bugs could be avoided by changing the server's default encoding, but thought I'd report it anyway.

**Comment by goodmami** [comment]
Thanks, @olzama, and please do report these, either here mentioning me or on PyDelphin's project. Anyway, I wasn't thorough enough in the last release. I looked for instances when files were read but not for when they were written. It's the same bug, just going the other way.

I've pushed a fix (probably... this is hard for me to test; I wasn't able to force Python to use ASCII as the default encoding) to the develop branch of PyDelphin. Before I cut a new release, can you `git clone https://github.com/delph-in/pydelphin.git` and install that to your virtual environment, then let me know if you encounter any other issues?

**Comment by olzama** [comment]
Thanks, Michael! I think it is @bmgraves who can do that.

**Comment by olzama** [comment]
Yay, the initial test (MiniEnglish->Create Grammar) passes!! Looks like the broad encoding issue has been resolved. Thanks, Michael!

**Comment by goodmami** [comment]
Great, thanks for confirming. I've now released the fix in PyDelphin as v1.5.1.

**Comment by olzama** [comment]
Here's another one (perhaps not related to pydelphin). This one I get by simply clicking on General Informaion, from an empty questionnaire:

<img width="1269" alt="Screen Shot 2021-01-07 at 11 19 30 AM" src="https://user-images.githubusercontent.com/10963114/103934893-a0744880-50da-11eb-9c39-94f5a44663e6.png">

**Comment by olzama** [comment]
Tagging @dantiston since he worked on the function `defs_to_html`; maybe he has an idea what could break there with python3!

**Comment by olzama** [comment]
Also, @bmgraves says: "The default encoding for the server is set to utf-8. If I test python, it tells me the default encoding is utf8. I have no idea why we are getting pushed into ascii".

**Comment by olzama** [comment]
The last issue I can sort of (temporarily) get around by doing:

```
print(self.defs_to_html(self.def_lines[section_begin:section_end],
                                    choices, vr,
                                    prefix='', vars={}).encode('utf-8'))
```

Although this results in the following (and still does not help avoid errors in the long run):

<img width="717" alt="Screen Shot 2021-01-07 at 11 50 56 AM" src="https://user-images.githubusercontent.com/10963114/103938219-c7cd1480-50de-11eb-9565-12b06f0fd569.png">

but at least it does not crash.

There are more problems however. I think I will open a new issue for those (if they are ultimately the same problem, we can close one as duplicate later).

**Comment by olzama** [comment]
The latest addition to this was fixed along with #552.
